#! /usr/bin/env/php

<?php

require_once __DIR__.'/../vendor/autoload.php';

use PS\Command\SetupCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new SetupCommand);
$application->run();
